### ISSUE TITLE
Long file names break the soundboard ui

### ISSUE THREAD

**Issue by krbz999** [Mythacri/Mythacri-Foundry-Scripts#64]
```css
.mythacri-scripts.soundboard .sound .sound-name {
  overflow: hidden;
  flex: 1;
}
```
